# Generated by Django 4.2.3 on 2023-07-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Gender', max_length=6)),
                ('semester', models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 7'), ('Semester 8', 'Semester 8')], max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('AIE', 'AIE'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('ELC', 'ELC'), ('MECH', 'MECH'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('MTECH', 'MTECH'), ('BCOM', 'BCOM'), ('MCOM', 'MCOM'), ('PHYSICS', 'PHYSICS'), ('CHEMISTRY', 'CHEMISTRY'), ('MATHS', 'MATHS'), ('MBBS', 'MBBS'), ('BAMS', 'BAMS'), ('BDS', 'BDS')], default='branch', max_length=10)),
                ('college_mail', models.EmailField(default='College mail', max_length=255)),
                ('phone_num', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
